### ISSUE TITLE
Slack is installed twice?

### ISSUE THREAD

**Issue by bitcrumb** [bramus/freshinstall#15]
It appears you're installing Slack twice. Once via the Mac App Store and once via `brew cask`.

![screen shot 2018-09-26 at 22 53 46](https://user-images.githubusercontent.com/135126/46108822-3ec89280-c1df-11e8-830d-ac3065470e0a.png)

**Comment by bramus** [comment]
Good catch. Fixed in 25edc9464cbc30030c9556a1784e60c8d39479e0.
