### ISSUE TITLE
random feedback

### ISSUE THREAD

**Issue by paulirish** [bramus/freshinstall#25]
I'd really recommend ssh multiplexing:

https://github.com/paulirish/dotfiles/blob/64c695666981866c8067d218181055c26bd355cd/.ssh.config.example#L7-L22

speeds up repeated github operations (assuming you do git over ssh).  and great if you ever create multiple ssh connections to a host.

----

i saw `reattach-to-user-namespace` and had recently run across that when wanting to do a `| pbcopy` while ssh'd.  none of the guides ive read explained it in a easy way for a tmux newb like myself.  do you have a recommendation?

also randomly.. you gotta try `ssh -CC`. if you're an iterm person (rather than base terminal), it's greattttttt. https://iterm2.com/documentation-tmux-integration.html

--- 

otherwise.. lookin cool!

i gave up on zsh a while ago, and have been a fish user for a while. (mostly cuz the default experience was better and didn't need to load in so many things to have a decent readline/prompt). but anyway.. next time i'm hacking up my zsh stuff i'll peek over here.

----------

oh and randomly. i have a (apparently private) repo which submodules in random other dotfiles repos. tbh it doesnt have to be submodules.. i just wanted to have a local clone of some folks stuff.. so that i can easily grep some quality repos for their solutions without resorting to searching ALL of github.  

<img width="933" alt="image" src="https://user-images.githubusercontent.com/39191/144504153-54f3bffd-6769-49d9-a654-58d87c0e56eb.png">

it's a useful lil resource.

okay great BYE

**Comment by paulirish** [comment]
oh and.. nice job making this into a satisfying lil package. :)

**Comment by bramus** [comment]
Hi @paulirish, thanks for the feedback. Always looking to improve things, so issues like these are very welcome :)

> ssh multiplexing

Great tip! Done.

> run across that when wanting to do a `| pbcopy` while ssh'd

Haven't encountered, but will keep an eye out for this.

> i gave up on zsh a while ago, and have been a fish user for a while.

Noticed your `.zshrc` was running a bit behind syntax-wise indeed, but with some minor adjustments it still stands. Heard great things about fish, should deffo check it out (one day).

> nice job making this into a satisfying lil package

Thanks :)
